# Generated by Django 2.2.6 on 2020-04-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200425_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link_video',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
