# Generated by Django 2.2.6 on 2019-10-30 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feriante', '0002_feriante_encargado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
        ('reserva', '0002_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('envio', models.BooleanField(blank=True, default=False)),
                ('feriante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaxferiante', to='feriante.Feriante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaxproducto', to='producto.Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaxuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
