# Generated by Django 2.2.6 on 2019-11-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='feriante',
        ),
    ]
