# Generated by Django 2.2.6 on 2019-11-03 22:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_remove_reserva_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8),
        ),
    ]
