# Generated by Django 2.2.6 on 2019-11-08 01:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from apps.feriante.models import Feriante


class Migration(migrations.Migration):

    dependencies = [
        ('feriante', '0004_merge_20191103_2151'),
        ('reserva', '0007_reserva_n_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='feriante',
            field=models.ForeignKey(default=Feriante.objects.get(pk = 1).pk, on_delete=django.db.models.deletion.CASCADE, to='feriante.Feriante'),
            preserve_default=False,
        ),
    ]
