# Generated by Django 2.2.6 on 2019-11-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_reserva_feriante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
