# Generated by Django 2.2.6 on 2019-11-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='direccion_de_envio',
            field=models.CharField(default='Alberdi 1525', max_length=200),
            preserve_default=False,
        ),
    ]
