# Generated by Django 2.2.6 on 2019-11-12 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tema', '0003_auto_20191111_2225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=500)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarioxforo', to='tema.Tema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarioxuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
