# Generated by Django 2.2.6 on 2019-11-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comentario_voto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='voto',
        ),
    ]
