# Generated by Django 2.2.6 on 2019-11-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='envio',
            field=models.BooleanField(default=False),
        ),
    ]
