# Generated by Django 2.2.6 on 2019-11-05 02:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8),
        ),
    ]
