# Generated by Django 2.2.6 on 2019-11-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='cantidad_respuesta',
            field=models.IntegerField(null=True),
        ),
    ]
