# Generated by Django 2.2.6 on 2019-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0002_auto_20191111_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='cantidad_respuesta',
            field=models.IntegerField(default=0),
        ),
    ]
