# Generated by Django 2.2.6 on 2019-10-30 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191025_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message=' El número de teléfono no es válido. ', regex='\\+?1?\\d{9,15}$')]),
        ),
    ]
