# Generated by Django 2.2.6 on 2019-11-28 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191030_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message=' El nombre no es válido. ', regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(default='cliente/user.png', null=True, upload_to='cliente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message=' El apellido no es válido. ', regex='[a-zA-Z]')]),
        ),
    ]
