# Generated by Django 2.2.6 on 2019-11-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='100$ por docena', max_length=100),
            preserve_default=False,
        ),
    ]
