# Generated by Django 2.2.6 on 2019-10-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='hola', upload_to='categoria'),
            preserve_default=False,
        ),
    ]
