# Generated by Django 2.2.6 on 2019-11-04 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriante', '0003_auto_20191103_1634'),
        ('feriante', '0003_auto_20191103_1929'),
    ]

    operations = [
    ]
